import { ExamPackage, MatrixRow, SpecRow } from '../types';

export const OFFICIAL_MATRIX_FOOTNOTES = [
  {
    symbol: '²',
    text: 'Mỗi câu hỏi bao gồm 4 ý nhỏ, mỗi ý học sinh phải chọn đúng hoặc sai. Một số tài liệu xếp loại câu hỏi này vào loại Nhiều lựa chọn phức hợp hoặc Nhiều lựa chọn có nhiều phương án đúng.',
  },
  {
    symbol: '³',
    text: 'Đối với môn học không sử dụng dạng này thì chuyển toàn bộ số điểm cho dạng “Đúng – Sai”.',
  },
  {
    symbol: '⁴',
    text: 'Có ở trong một số ô của ma trận, thể hiện số câu hỏi hoặc câu hỏi số bao nhiêu.',
  },
  {
    symbol: '⁵',
    text: 'Lựa chọn sao cho được khoảng 3,0 điểm, tương ứng với tỉ lệ khoảng 30%; tương tự như thế đối với các dạng khác.',
  },
];

export const OFFICIAL_SPEC_FOOTNOTES = [
  {
    symbol: '⁶',
    text: 'Có ở trong một số ô của bản đặc tả, ghi tắt tên của năng lực (đã được quy định trong chương trình môn học/hoạt động giáo dục).',
  },
];

/**
 * Tạo dữ liệu mẫu Đề kiểm tra định kì chuẩn 100% theo mẫu của Bộ Giáo dục & Đào tạo
 */
export function getOfficialSampleExamPackage(): ExamPackage {
  const sampleMatrix: MatrixRow[] = [
    {
      stt: 1,
      topic: 'Chủ đề 1: Hàm số và đồ thị',
      subTopic: 'Hàm số bậc hai và đồ thị',
      part1: { remember: 2, understand: 1, apply: 0, advanced: 0 },
      part2: { remember: 0, understand: 1, apply: 0, advanced: 0 },
      part3: { remember: 0, understand: 1, apply: 0, advanced: 0 },
      part4: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      totalQuestions: 4,
      totalPoints: 2.0,
      percentage: 20,
      cellTexts: {
        p1_rem: '2',
        p1_und: '1',
        p2_und: '(1)',
        p3_und: '(1)',
      },
    },
    {
      stt: 1,
      topic: 'Chủ đề 1: Hàm số và đồ thị',
      subTopic: 'Dấu của tam thức bậc hai & bất phương trình bậc hai',
      part1: { remember: 2, understand: 1, apply: 0, advanced: 0 },
      part2: { remember: 0, understand: 0, apply: 1, advanced: 0 },
      part3: { remember: 0, understand: 0, apply: 1, advanced: 0 },
      part4: { remember: 0, understand: 0, apply: 1, advanced: 0 },
      totalQuestions: 5,
      totalPoints: 2.75,
      percentage: 27.5,
      cellTexts: {
        p1_rem: '2',
        p1_und: '1',
        p2_app: '(n)⁴',
        p3_app: '(1)',
        p4_app: '(1)',
      },
    },
    {
      stt: 2,
      topic: 'Chủ đề 2: Đại số tổ hợp',
      subTopic: 'Quy tắc cộng, quy tắc nhân và sơ đồ hình cây',
      part1: { remember: 3, understand: 1, apply: 0, advanced: 0 },
      part2: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      part3: { remember: 0, understand: 1, apply: 0, advanced: 0 },
      part4: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      totalQuestions: 4,
      totalPoints: 1.5,
      percentage: 15,
      cellTexts: {
        p1_rem: '3',
        p1_und: '1',
        p3_und: '(1)',
      },
    },
    {
      stt: 2,
      topic: 'Chủ đề 2: Đại số tổ hợp',
      subTopic: 'Hoán vị, chỉnh hợp và tổ hợp',
      part1: { remember: 2, understand: 1, apply: 0, advanced: 0 },
      part2: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      part3: { remember: 0, understand: 0, apply: 1, advanced: 0 },
      part4: { remember: 0, understand: 0, apply: 1, advanced: 0 },
      totalQuestions: 4,
      totalPoints: 2.25,
      percentage: 22.5,
      cellTexts: {
        p1_rem: '2',
        p1_und: '1',
        p3_app: '(1)',
        p4_app: '(1)',
      },
    },
    {
      stt: '...',
      topic: 'Chủ đề ....',
      subTopic: 'Nội dung kiến thức bổ trợ',
      part1: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      part2: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      part3: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      part4: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      totalQuestions: 0,
      totalPoints: 0,
      percentage: 0,
    },
  ];

  const sampleSpec: SpecRow[] = [
    {
      stt: 1,
      topic: 'Chủ đề 1: Hàm số và đồ thị',
      subTopic: 'Hàm số bậc hai và đồ thị',
      requirements: `- Biết:\nNhận biết được các khái niệm về hàm số bậc hai, đỉnh, trục đối xứng và hướng bề lõm của parabol.\n\n- Hiểu:\nXác định được khoảng đồng biến, khoảng nghịch biến của hàm số bậc hai; vẽ được đồ thị parabol.\n\n- Vận dụng:\nVận dụng đồ thị hàm số để giải quyết một số bài toán thực tế đơn giản về độ cao cực đại, tầm xa.`,
      part1: { remember: 2, understand: 1, apply: 0, advanced: 0 },
      part2: { remember: 0, understand: 1, apply: 0, advanced: 0 },
      part3: { remember: 0, understand: 1, apply: 0, advanced: 0 },
      part4: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      totalPoints: 2.0,
      competency: 'NL_gqvđ',
      cellTexts: {
        p1_rem: '2',
        p1_und: '1',
        p2_und: '(1)\n(NL_mhh)⁶',
        p3_und: '(1)\n(NL_tt)⁶',
      },
    },
    {
      stt: 1,
      topic: 'Chủ đề 1: Hàm số và đồ thị',
      subTopic: 'Dấu của tam thức bậc hai & bất phương trình bậc hai',
      requirements: `- Biết:\nNhận biết được dấu của tam thức bậc hai và nghiệm của phương trình bậc hai tương ứng.\n\n- Hiểu:\nGiải được bất phương trình bậc hai một ẩn; tìm điều kiện tham số để tam thức không đổi dấu.\n\n- Vận dụng:\nGiải quyết một số bài toán gắn với thực tiễn liên quan đến bất phương trình bậc hai.`,
      part1: { remember: 2, understand: 1, apply: 0, advanced: 0 },
      part2: { remember: 0, understand: 0, apply: 1, advanced: 0 },
      part3: { remember: 0, understand: 0, apply: 1, advanced: 0 },
      part4: { remember: 0, understand: 0, apply: 1, advanced: 0 },
      totalPoints: 2.75,
      competency: 'NL_mhh',
      cellTexts: {
        p1_rem: '2',
        p1_und: '1',
        p2_app: '(n)\n(NL?)⁶',
        p3_app: '(1)\n(NL_gqvđ)⁶',
        p4_app: '(1)\n(NL_mhh)⁶',
      },
    },
    {
      stt: 2,
      topic: 'Chủ đề 2: Đại số tổ hợp',
      subTopic: 'Quy tắc cộng, quy tắc nhân và sơ đồ hình cây',
      requirements: `- Biết:\nNhận biết và phân biệt được quy tắc cộng và quy tắc nhân trong các tình huống đếm đơn giản.\n\n- Hiểu:\nVận dụng quy tắc cộng và quy tắc nhân trong việc giải các bài toán đếm các đối tượng cơ bản.\n\n- Vận dụng:\nGiải quyết một số bài toán tổ hợp đếm phương án thực tế.`,
      part1: { remember: 3, understand: 1, apply: 0, advanced: 0 },
      part2: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      part3: { remember: 0, understand: 1, apply: 0, advanced: 0 },
      part4: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      totalPoints: 1.5,
      competency: 'NL_tt',
      cellTexts: {
        p1_rem: '3',
        p1_und: '1',
        p3_und: '(1)\n(NL_tt)⁶',
      },
    },
    {
      stt: 2,
      topic: 'Chủ đề 2: Đại số tổ hợp',
      subTopic: 'Hoán vị, chỉnh hợp và tổ hợp',
      requirements: `- Biết:\nNhận biết định nghĩa và công thức tính số hoán vị $P_n$, chỉnh hợp $A_n^k$, tổ hợp $C_n^k$.\n\n- Hiểu:\nPhân biệt khi nào dùng chỉnh hợp, khi nào dùng tổ hợp trong bài toán đếm có thứ tự và không thứ tự.\n\n- Vận dụng:\nGiải bài toán đếm tổ hợp kết hợp nhiều điều kiện thực tế (chia đội, chọn người, lập số tự nhiên).`,
      part1: { remember: 2, understand: 1, apply: 0, advanced: 0 },
      part2: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      part3: { remember: 0, understand: 0, apply: 1, advanced: 0 },
      part4: { remember: 0, understand: 0, apply: 1, advanced: 0 },
      totalPoints: 2.25,
      competency: 'NL_gqvđ',
      cellTexts: {
        p1_rem: '2',
        p1_und: '1',
        p3_app: '(1)\n(NL_gqvđ)⁶',
        p4_app: '(1)\n(NL_gqvđ)⁶',
      },
    },
    {
      stt: '...',
      topic: 'Chủ đề ....',
      subTopic: 'Nội dung kiến thức bổ trợ',
      requirements: `- Biết...\n...\n- Hiểu...\n...\n- VD...\n...`,
      part1: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      part2: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      part3: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      part4: { remember: 0, understand: 0, apply: 0, advanced: 0 },
      totalPoints: 0,
    },
  ];

  return {
    id: 'official_sample_template',
    createdAt: new Date().toISOString(),
    metadata: {
      schoolName: 'TRƯỜNG THCS & THPT KIỂM TRA',
      departmentName: 'SỞ GIÁO DỤC VÀ ĐÀO TẠO',
      subject: 'Toán',
      grade: 'Khối 10',
      className: '10A1',
      semester: 'Học kỳ I',
      schoolYear: '2026 - 2027',
      examTitle: 'ĐỀ KIỂM TRA ĐỊNH KÌ',
      chapterTitle: 'Hàm số và đồ thị - Đại số tổ hợp',
      durationMinutes: 90,
      totalPoints: 10.0,
      curriculum: 'Kết nối tri thức với cuộc sống',
      examMode: 'MCQ_ESSAY',
      codeCount: 1,
      questionCounts: {
        part1_MCQSingle: 12,
        part1_PointsPerQuestion: 0.25,
        part2_MCQTrueFalse: 2,
        part2_PointsPerQuestion: 1.0,
        part2_TFStatementsPerQuestion: 4,
        part3_MCQShort: 4,
        part3_PointsPerQuestion: 0.5,
        part4_Essay: 2,
        part4_ApplyPoints: 1.5,
        part4_AdvancedPoints: 1.5,
      },
      cognitiveRatio: {
        remember: 40,
        understand: 30,
        apply: 30,
        advanced: 0,
      },
    },
    matrix: sampleMatrix,
    specification: sampleSpec,
    exams: [
      {
        code: '101',
        questions: [
          {
            id: 'q_p1_1',
            partType: 'PART1',
            partTitle: 'PHẦN I. Câu trắc nghiệm nhiều phương án lựa chọn',
            number: 1,
            content: 'Tọa độ đỉnh của parabol $y = x^2 - 4x + 3$ là:',
            cognitiveLevel: 'REMEMBER',
            points: 0.25,
            topic: 'Hàm số bậc hai và đồ thị',
            options: [
              { key: 'A', content: '$I(2; -1)$' },
              { key: 'B', content: '$I(-2; 15)$' },
              { key: 'C', content: '$I(4; 3)$' },
              { key: 'D', content: '$I(1; 0)$' },
            ],
            correctOption: 'A',
            explanation: 'Hoành độ đỉnh $x_I = -\\frac{b}{2a} = 2$, tung độ $y_I = -1$.',
          },
        ],
      },
    ],
    answerKeys: [
      {
        code: '101',
        part1Answers: [
          { questionNumber: 1, correctOption: 'A', points: 0.25 },
        ],
        part2Answers: [],
        part3Answers: [],
        part4Answers: [],
      },
    ],
  };
}
